export const appSounds = {
  click: `../../../assets/sounds/tick.mp3`,
  bassDrum: `../../../assets/sounds/tunn.mp3`,
  snare: `../../../assets/sounds/snare.mp3`,
  snareSidestick: `../../../assets/sounds/side-stick.mp3`,
  hiHat: `../../../assets/sounds/hi-hat.mp3`,
  ride: "../../../assets/sounds/ride.mp3",
  rideBell: "../../../assets/sounds/ride-bell.mp3",
  shake: `../../../assets/sounds/shake.mp3`,
  cowbell1: "../../../assets/sounds/cuba_cowbell.mp3",
  cowbell2: "../../../assets/sounds/light_cowbell.mp3",
  woodblock: "../../../assets/sounds/wood_block.mp3",
  timbale1: "../../../assets/sounds/timbale.mp3",
  timbale2: "../../../assets/sounds/timbale2.mp3",
  metal: "../../../assets/sounds/metal.mp3",
};
